CFLAGS=-Wall -g

# Clean before making!
all: clean
	make ex2

# Remove the ex2 file and also the .dSYM dir.
clean:
	rm -f ex2
	rm -rf ex2.dSYM

    # Also remove the extra credit file
	rm -f extra
	rm -rf extra.dSYM

extra_credit:
	make extra

# Note: this is an infinite loop!
hello:
	make hello